<?php if(isset($categoryList) && is_array($categoryList) && isset($tab) && isset($parent_id)){ ?>
    <?php foreach($categoryList as $item){ ?>
        <?php $setDisabled = (bool)(isset($disabled) && $disabled == true && isset($item['subcategory'])); ?>
        <option<?php echo($setDisabled == true ? ' disabled="disabled"' : ''); ?> value="<?php echo($item['id']); ?>"<?php echo(($item['id']==$parent_id && $setDisabled == false) ? ' selected="selected"' : ''); ?>><?php echo($tab.$item['name']); ?></option>
        <?php if(isset($item['subcategory'])){ ?>
        <?php echo($this->partial('admin/catalog/category/edit-category-select.phtml', array('categoryList' => $item['subcategory'], 'parent_id' => $parent_id, 'tab' => $tab.'&nbsp;&bull;&nbsp;', 'disabled' => $setDisabled))); ?>
        <?php } ?> 
    <?php } ?>
<?php } ?>