<div class="wrapper">
    <div class="wrapper-center">
        <div class="container">
            <h2 class="lk-title">Личный кабинет</h2>

            <div class="lk">
                <?php echo($this->partial('profile-partials/tabs-menu.phtml')); ?>
                <div class="tab-content uslugi kab">
                    <div class="error-text" id="tab2">
                        Произошла ошибка при сохранении изменений
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>