<?php echo($this->partial('partials/vehicles-content-menu.phtml', array('vehiclesCat' => $vehiclesCat))); ?>
<?php echo($this->partial('profile-partials/tabs-menu.phtml')); ?>
<div class="tab-content">
    <section class="tab-item">
        <div class="section-content">
            <h1 class="section-heading">Укажите Ваше имя или имя контактного лица, с которым мы могли бы связаться</h1>
            <form action="<?php echo($this->easyUrl(array('action' => 'edit'))); ?>" class="form contacts-form" method="post" autocomplete="off">
                <fieldset>
                    <div class="two-columns">
                        <div class="col">
                            <div class="row">
                                <label>Имя</label>
                                <input type="text" class="name-item" name="name" value="<?php echo(isset($getEdit['name']) ? $getEdit['name'] : ''); ?>" maxlength="100">
                            </div>
                        </div>
                        <div class="col">
                            <?php echo($this->partial('profile-partials/user-phone-box.phtml')); ?>
                        </div>
                    </div>
                    <div class="submit-holder">
                        <input type="submit" value="Сохранить">
                    </div>
                </fieldset>
                <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
                <input type="hidden" name="contacts-form" value="0">
            </form>
        </div>
    </section>
</div>