<?php echo($this->partial('partials/vehicles-content-menu.phtml', array('vehiclesCat' => $vehiclesCat))); ?>
<?php echo($this->partial('profile-partials/tabs-menu.phtml')); ?>
<div class="tab-content">
    <section class="tab-item">
        <div class="section-content">
            <fieldset>
                <h2>Контактная информация</h2>
                <div class="row-holder">
                    <div class="row">
                        Изменения успешно сохранены
                    </div>
                </div>
            </fieldset>
        </div>
    </section>
</div>