<form class="form-validator add" action="<?php echo($this->easyUrl(array('action' => 'city-add'))); ?>" method="post">
    <fieldset>
        <legend>Добавление города</legend>
        <div class="control-group">
            <label class="control-label">Регион</label>
            <div class="controls">
                <select class="selectpicker" name="region_id">
                    <?php foreach($regionList as $item){ ?>
                        <option value="<?php echo($item['id']); ?>"><?php echo($item['name']); ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Название</label>
            <div class="controls">
                <input type="text" name="name" placeholder="Введите текст…" maxlength="20" value="">
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'city'))); ?>">Отменить</a>
        </div>
    </fieldset>
    <input type="hidden" name="add-form" value="0">
    <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
</form>
