<form class="form-validator edit" action="<?php echo($this->easyUrl(array('action' => 'edit-region', 'id' => $getOne['id']))); ?>" method="post">
    <fieldset>
        <legend>Добавление региона</legend>
        <div class="control-group">
            <label class="control-label">Название</label>
            <div class="controls">
                <input type="text" name="name" placeholder="Введите текст…" maxlength="20" value="<?php echo $getOne['name']; ?>">
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'index'))); ?>">Отменить</a>
        </div>
    </fieldset>
    <input type="hidden" name="edit-form" value="0">
    <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
</form>
