<?php echo($this->partial('admin/locations/tab-nav.phtml')); ?>
<div class="row-fluid">
    <div class="col span6">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Название</th>
                <th class="action-box"></th>
            </tr>
            </thead>
            <?php if($paramsList){ ?>
                <?php foreach($paramsList as $item){ ?>
                    <tr>
                        <td><?php echo $item['name']; ?></td>
                        <td class="action-box">
                            <a href="<?php echo($this->easyUrl(array('action' => 'edit-region', 'id' => $item['id']))); ?>" class="icon-edit" title="редактировать"></a>
                            <a href="<?php echo($this->easyUrl(array('action' => 'remove-region', 'id' => $item['id']), array(), true)) ?>" class="icon-remove confirm-remove" title="удалить"></a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>
        </table>
    </div>
</div>