<div class="wrapper">
    <div class="wrapper-center">
        <div class="container">
            <div class="wblock">
                <div class="content">
                    <h3>Ошибка</h3>

                    <p class="error-text">Произошла ошибка при регистрации, возможно некоторые данные были указаны не
                        корректно.</p>
                </div>
            </div>
        </div>
    </div>
</div>