<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Site Name'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <!-- Le styles -->
        <?php 
            $this->headLink(array(
                         'rel' => 'shortcut icon', 
                         'type' => 'image/png', 
                         'href' => $this->basePath() . '/img/favicon.png'
                  ))
                  ->prependStylesheet($this->basePath() . '/css/lightbox.css') 
                  ->prependStylesheet($this->basePath() . '/css/bootstrap-formhelpers.css')
                  ->prependStylesheet($this->basePath() . '/css/bootstrap-select.min.css')
                  ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                  ->prependStylesheet($this->basePath() . '/css/style.css')
                  ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');



            $this->headScript()
                 ->prependFile($this->basePath() . '/js/default.js')
                 ->prependFile($this->basePath() . '/js/libs/bootstrap-formhelpers-phone.js')
                 ->prependFile($this->basePath() . '/js/libs/bootstrap-select.min.js')
                 ->prependFile($this->basePath() . '/js/tinymce/jquery.tinymce.min.js')
                 ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                 ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                 ->prependFile($this->basePath() . '/js/jquery.main.js') 
                 ->prependFile($this->basePath() . '/js/libs/lightbox-2.6.min.js') 
                 ->prependFile($this->basePath() . '/js/libs/modernizr-2.6.2.min.js') 
                 ->prependFile($this->basePath() . '/js/libs/jquery-1.10.2.min.js'); 

            $this->mediaLoader();
            
            echo($this->headLink()."\n");
            echo($this->headScript()."\n");
        ?>
    </head>
    <body>
        <?php echo($this->partial('admin/layout/header')); ?>
        <div class="container-fluid">
            <?php if(isset($_SESSION['admin']->auth['id'])){ ?>
                <div class="row-fluid">
                    <div class="span2">
                      <?php echo($this->partial('admin-partials/sidebar-nav.phtml')); ?>
                    </div>
                    <div class="span10">
                      <?php echo($this->content); ?>
                    </div>
                </div>
            <?php }else{ ?>
                <?php echo($this->content); ?>
            <?php } ?>
        </div> <!-- /container -->
        <?php echo($this->inlineScript()); ?>
    </body>
</html>
