<form autocomplete="off" method="post" action="<?php echo($this->easyUrl(array('module' => 'profile', 'controller' => 'registration'))); ?>" class="popup register">
  <div class="row">
      <label for="inputUser">Эл. почта</label>
      <input type="text" maxlength="100" value="" placeholder="" name="username" id="inputUser">
  </div>
  <div class="row">
      <label for="inputPassword">Пароль</label>
      <input type="password" maxlength="100" value="" placeholder="" name="password" id="inputPassword">
  </div>
  <div class="row">
      <label for="inputRetryPassword">Повторите пароль</label>
      <input type="password" maxlength="100" value="" placeholder="" name="retry_password" id="inputRetryPassword">
  </div>
  <div class="submit-holder">
        <input type="submit" value="Регистрация">
  </div>
  <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('module' => 'profile', 'controller' => 'registration', 'action' => 'validator'))); ?>">
  <input type="hidden" name="registration-form" value="0">
</form>