<div class="login-holder<?php echo(isset($_SESSION['profile']->auth['id']) ? ' logged' : ''); ?>">
    <?php if(isset($_SESSION['profile']->auth['id'])){ ?>
        <a href="<?php echo($this->easyUrl(array('module' => 'profile', 'controller' => 'login', 'action' => 'logout'))); ?>" class="btn-login">Выход</a>
        <div class="user-details">
            <div class="username">
                <a href="<?php echo($this->easyUrl(array('module' => 'profile'))); ?>"><?php echo($_SESSION['profile']->auth['username']); ?></a>
            </div>
            <div class="other">
                <span class="item">Баланс: <span class="stars"><?php echo(isset($_SESSION['profile']->star) ? (int)$_SESSION['profile']->star : 0); ?></span></span>
                <span class="item">Объявлений: <?php echo(isset($_SESSION['profile']->carsCount) ? (int)$_SESSION['profile']->carsCount : 0); ?></span>
            </div>
        </div>
    <?php }else{ ?>
        <a class="btn-login">Вход</a>
        <?php echo($this->partial('profile-partials/form-login.phtml')); ?>
        <?php echo($this->partial('profile-partials/form-forgot.phtml')); ?>
        <?php echo($this->partial('profile-partials/form-register.phtml')); ?>
    <?php } ?>
</div>