<div class="row">
    <label class="label-top">Телефон</label>
    <div class="phone-container">                                    
        <?php 
               $phoneCount = 0; 
               if(isset($getPhone) && is_array($getPhone)){ 
                   $phoneCount = sizeof($getPhone); 
         ?> 
            <div class="phone-list">
            <?php foreach($getPhone as $item){ ?>
              <div class="row">
                <?php echo($item['phone']); ?> &nbsp; <a class="phone-remove-item" href="<?php echo($this->easyUrl(array('action' => 'remove-phone', 'id' => $item['id']))); ?>">удалить</a>
              </div>
            <?php } ?>
            </div>
        <?php } ?>
        <div class="phone-box">
            <?php if($phoneCount < 5){ ?>
            <div class="row control-group">
                <input type="text" class="phone-items bfh-phone small" data-format="<?php echo(isset($phoneMask) ? $phoneMask : ''); ?>" name="phone[]" placeholder="<?php echo(isset($phonePlaceholder) ? $phonePlaceholder : ''); ?>" maxlength="20" value="">
                <?php if(isset($phoneMaskArray) && is_array($phoneMaskArray)){ ?>
                  <select class="phone-change-mask small" name="mask[]">                    
                    <?php foreach($phoneMaskArray as $item){ ?>
                        <option value="<?php echo($item['id']); ?>" data-mask="<?php echo($item['mask']); ?>"><?php echo($item['placeholder']); ?></option>
                    <?php } ?>
                  </select>
                <?php } ?>
            </div>
            <?php } ?>
        </div>
    </div>
</div>
<input type="hidden" class="phone-item-data" data-phone-mask="<?php echo(isset($phoneMask) ? $phoneMask : ''); ?>" data-phone-placeholder="<?php echo(isset($phonePlaceholder) ? $phonePlaceholder : ''); ?>">
<a class="add-number phone-add-item">Добавить номер</a>
