<form class="form-validator edit" action="<?php echo($this->easyUrl(array('action' => 'edit', 'id' => $getEdit['category_id']))); ?>" method="post">
    <fieldset>
        <legend>Добавить</legend>
        <div class="control-group">
            <label class="control-label">Рубрика</label>
            <div class="controls">
                <?php if ($getCategory) { ?>
                    <select class="selectpicker edit-require span3" name="category_id">
                        <?php echo($this->partial('admin/catalog/category/edit-category-select.phtml', array('categoryList' => $getCategory, 'tab' => '', 'disabled' => false, 'parent_id' => $getEdit['category_id']))); ?>
                    </select>
                <?php } ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Поля</label>
            <div class="controls">
                <input type="checkbox" <?php echo (in_array('description', $getEdit['fields']) ? 'checked="checked"' : ''); ?> value="y" name="params[description]"> Описание
            </div>
            <div class="controls">
                <input type="checkbox" <?php echo (in_array('phone', $getEdit['fields']) ? 'checked="checked"' : ''); ?> value="y" name="params[phone]"> Телефон
            </div>
            <div class="controls">
                <input type="checkbox" <?php echo (in_array('price', $getEdit['fields']) ? 'checked="checked"' : ''); ?> value="y" name="params[price]"> Цена
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'index'))); ?>">Отменить</a>
        </div>
    </fieldset>
    <input type="hidden" name="edit-form" value="1">
    <input type="hidden" name="edit-require-url" value="<?php echo $this->easyUrl(array('action' => 'get-fields')); ?>">
</form>
