
<div class="row-fluid">
    <div class="col span6">
        <div class="control-group">
            <a href="<?php echo $this->easyUrl(array('action' => 'add')); ?>" class="btn btn-info">Добавить</a><br>
        </div>
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Рубрика</th>
                <th>Поля</th>
                <th class="action-box"></th>
            </tr>
            </thead>
            <?php if($paramsList){ ?>
                <?php foreach($paramsList as $item){ ?>
                    <tr>
                        <td>
                            <?php if(isset($item['breadcrumbs']) && is_array($item['breadcrumbs'])){ ?>
                                <?php echo($this->partial('admin/catalog/category/breadcrumbs.phtml', array('breadcrumbs' => $item['breadcrumbs'], 'unlink' => true))); ?>
                            <?php }else{ ?>
                                <?php echo $item['category_name']; ?>
                            <?php } ?>
                        </td>
                        <td><?php echo $item['fields']; ?></td>
                        <td class="action-box">
                            <a href="<?php echo($this->easyUrl(array('action' => 'edit', 'id' => $item['category_id']))); ?>" class="icon-edit" title="редактировать"></a>
                            <a href="<?php echo($this->easyUrl(array('action' => 'remove', 'id' => $item['category_id']), array(), true)) ?>" class="icon-remove confirm-remove" title="удалить"></a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>
        </table>
    </div>
</div>