<?php if($getEdit){ ?>
<form class="type-form-validator edit" action="<?php echo($this->easyUrl(array('id' => $getEdit['id']))); ?>" method="post">
  <fieldset>
    <legend>Редактирование типа</legend>
    <div class="control-group">        
        <label class="control-label">Название</label>
        <div class="controls">
            <input type="text" class="span3" name="name" placeholder="Введите текст…" maxlength="50" value="<?php echo($getEdit['name']); ?>">
        </div>
    </div>
    <div class="control-group">
      <label class="control-label">Раздел</label>
      <div class="controls">
          <select class="selectpicker span3" name="catalog">
              <?php foreach ($mainCategory as $item) { ?>
                  <option <?php echo ($getEdit['catalog'] == $item['id'] ? 'selected="selected"' : ''); ?> value="<?php echo($item['id']); ?>"><?php echo($item['name']); ?></option>
              <?php } ?>
          </select>
      </div>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Сохранить</button>
      <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'type'))); ?>">Отменить</a>
    </div>
  </fieldset>
  <input type="hidden" name="edit-form" value="0">
  <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'type-validator'))); ?>">
</form>
<?php }else{ ?>
<h3>Нет данных</h3>
<?php } ?>
