<?php echo($this->partial('admin/catalog/tab-nav.phtml')); ?>
<?php if($typeList){ ?>
<div class="row-fluid">
    <div class="col">      
        <table class="table table-striped table-bordered">
            <thead>        
                <tr>
                    <th>Тип</th>
                    <th class="action-box"></th>
                </tr>
            </thead>
            <?php foreach($typeList as $item){ ?>
            <tr>
                <td><?php echo($item['name']); ?></td>
                <td class="action-box">
                   <a href="<?php echo($this->easyUrl(array('action' => 'type-edit', 'id' => $item['id']))) ?>" class="icon-edit" title="редактировать"></a>
                   <a href="<?php echo($this->easyUrl(array('action' => 'type-remove', 'id' => $item['id']))) ?>" class="icon-remove confirm-remove" title="удалить"></a>
                </td>
            </tr>
            <?php } ?> 
        </table>
    </div>
</div>
<?php } ?>