<div class="wrapper">
    <div class="wrapper-center">
        <div class="container">
        <?php if ($content) { ?>
            <div class="tab-content">
                <h4><?php echo ($content['title']); ?></h4>
                <p>
                    <?php echo ($content['content']); ?>
                </p>
        <?php } else { ?>
            <p> Данных нет </p>
        <?php } ?>
            </div>
        </div>
    </div>
</div>