<div class="wrapper">
    <div class="wrapper-center">
        <div class="container">
            <h2 class="lk-title">Личный кабинет</h2>

            <div class="lk">
                <?php echo($this->partial('profile-partials/tabs-menu.phtml')); ?>
                <div class="tab-content uslugi kab">
                    <div id="tab3">
                        Для подтверждения смены электронной почты перейдите по ссылке которая была отправлена на ваш
                        старый электронный адрес.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>