<?php echo($this->partial('profile-partials/tabs-menu.phtml')); ?>
<div class="tab-content">
    <section class="tab-item">
        <div class="section-content">
            <h1 class="section-heading">Информация профиля</h1>
            <form action="<?php echo($this->easyUrl(array('action' => 'edit'))); ?>" class="form settings-form" method="post" autocomplete="off">
                <fieldset>
                    <div class="two-columns">
                        <div class="col">
                            <div class="row">
                                <label>Эл. почта</label>
                                <input type="email" name="username" value="<?php echo(isset($getEdit['username']) ? $getEdit['username'] : ''); ?>" maxlength="100">
                            </div>
                        </div>
                        <div class="col">
                            <div class="row">
                                <label>Текущий пароль</label>
                                <input type="password" name="old_password" value="" maxlength="100">
                            </div>
                            <div class="row">
                                <label>Новый пароль</label>
                                <input type="password" name="password" value="" maxlength="100">
                            </div>
                            <div class="row">
                                <label>Подтвердите пароль</label>
                                <input type="password" name="retry_password" value="" maxlength="100">
                            </div>
                        </div>
                    </div>
                    <div class="submit-holder">
                        <input type="submit" value="Сохранить">
                    </div>
                </fieldset>
                <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
                <input type="hidden" name="settings-form" value="0">
            </form>
        </div>
    </section>
</div>