<div class="wrapper">
    <div class="wrapper-center">
        <div class="container">
            <h2 class="lk-title">Личный кабинет</h2>

            <div class="lk">
                <?php echo($this->partial('profile-partials/tabs-menu.phtml')); ?>
                <div class="tab-content uslugi kab">
                    <div id="tab3">
                        <h2 class="t-dotted">Информация профиля
                        </h2>

                        <div class="wrap t-dotted">
                            <form action="<?php echo($this->easyUrl(array('action' => 'edit'))); ?>" class="profile">
                                <div class="col">
                                    <label for="mail">Эл. почта</label>

                                    <div class="input-holder username">
                                        <input name="username" id="mail" type="text"
                                               value="<?php echo(isset($getEdit['username']) ? $getEdit['username'] : ''); ?>"
                                               maxlength="100" placeholder="Введите эл. почту"/>
                                        <span>* Заполните обязательное поле</span>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="wrap">
                                        <label for="pasw_now">Текущий пароль<span>*</span></label>

                                        <div class="input-holder old_password">
                                            <input name="old_password" value="" maxlength="100" id="pasw_now"
                                                   type="password" placeholder="Введите текущий пароль"/>
                                            <span>* Проверьте правильность заполнения поля</span>
                                        </div>
                                    </div>
                                    <div class="wrap">
                                        <label for="pasw_new">Новый пароль<span>*</span></label>

                                        <div class="input-holder password">
                                            <input name="password" value="" maxlength="100" id="pasw_new"
                                                   type="password" placeholder="Введите новый пароль"/>
                                            <span>* Проверьте правильность заполнения поля</span>
                                        </div>
                                    </div>
                                    <div class="wrap">
                                        <label for="pasw_now_repeat">Повторите пароль<span>*</span></label>

                                        <div class="input-holder retry_password">
                                            <input name="retry_password" value="" maxlength="100" id="pasw_now_repeat"
                                                   type="password" placeholder="Введите новый пароль ещё раз"/>
                                            <span>* Проверьте правильность заполнения поля</span>
                                        </div>
                                    </div>
                                </div>
                                <input type="hidden" name="validator"
                                       value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
                                <input type="hidden" name="settings-form" value="0">
                                <input type="submit" style="display: none;">
                            </form>
                        </div>
                        <a class="submitIt" href="#">Сохранить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>