<?php if($getEdit){ ?>
    <form class="contact-us-edit-form" action="<?php echo($this->easyUrl(array('id' => $getEdit['id']))); ?>" method="post">
        <fieldset>
            <legend>Редактирование отзыва</legend>
            <div class="control-group">        
                <label class="control-label">Имя</label>
                <div class="controls">
                    <input class="span6" type="text" name="name" placeholder="Введите имя…" maxlength="100" value="<?php echo($getEdit['name']); ?>">
                </div>
            </div>
            <div class="control-group">        
                <label class="control-label">Email</label>
                <div class="controls">
                    <input class="span6" type="email" name="email" placeholder="Введите email…" maxlength="100" value="<?php echo($getEdit['email']); ?>">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Сообщение</label>
                <div class="controls">
                    <textarea name="message" class="textarea-fix-size span6" maxlength="10000" placeholder="Введите текст…" rows="15"><?php echo($getEdit['message']); ?></textarea>
                </div>
            </div>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'index'))); ?>">Отменить</a>
            </div>
        </fieldset>
        <input type="hidden" name="edit-form" value="0">
        <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
    </form>
<?php }else{ ?>
    <h3>Нет данных</h3>
<?php } ?>