<div class="row-fluid">
    <?php if ($contactUsList) { ?>
        <div class="col">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Дата</th>
                    <th>Имя</th>
                    <th>Email</th>
                    <th>Сообщение</th>
                    <th class="action-box"></th>
                </tr>
                </thead>
                <?php foreach ($contactUsList as $item) { ?>
                    <tr>
                        <td><?php echo($item['date']); ?></td>
                        <td><?php echo($item['name']); ?></td>
                        <td><?php echo($item['email']); ?></td>
                        <td><?php echo($item['message']); ?></td>
                        <td class="action-box">
                            <a href="<?php echo($this->easyUrl(array('action' => 'edit', 'id' => $item['id']))) ?>" class="icon-edit" title="редактировать"></a>
                            <a href="<?php echo($this->easyUrl(array('action' => 'remove', 'id' => $item['id']))) ?>" class="icon-remove confirm-remove" title="удалить"></a>
                        </td>
                    </tr>
                <?php } ?>
            </table>
            <?php echo($this->partial('admin-partials/paginator.phtml', array('paginator' => $paginator))); ?>
        </div>
    </div>
<?php } ?>