<?php if(isset($getGallery) && is_array($getGallery)){ ?>
<div class="item-gallery">
    <div class="left-bar">
        <a class="btn-prev">previous</a>
        <div class="pager-holder">
            <ul class="pager">  
            <?php foreach($getGallery as $item){ ?>
                <?php if(isset($item['slider']['small'])){ ?>
                <li>
                    <a><img class="gal-img" src="<?php echo($item['slider']['small']); ?>" alt=""></a>
                </li>
                <?php } ?>
            <?php } ?>
            </ul>
        </div>
        <a class="btn-next">next</a>
    </div>
    <div class="holder">
        <ul>
        <?php foreach($getGallery as $item){ ?>
            <?php if(isset($item['slider']['medium'])){ ?>
            <li>
                <a href="<?php echo($item['url']); ?>" data-lightbox="place-gallery">
                    <img class="gal-img" src="<?php echo($item['slider']['medium']); ?>" alt="">
                </a>
            </li>
            <?php } ?>
        <?php } ?>
        </ul>
    </div>
</div>
<?php } ?>