<a href="<?php echo($this->easyUrl(array('module' => 'profile', 'controller' => (($this->session('profile')->authId !== null) ? 'index' : 'guest'), 'action' => 'add', 'catalog' => (isset($catalogUrl) ? $catalogUrl : 'uslugi')))); ?>" class="new_adverticement">
    <span></span> подать объявление
</a>
<ul class="tabset uslugi">
    <?php if ($typeList) { ?>
        <?php foreach ($typeList as $item) { ?>
            <li>
                <a href="<?php echo($this->easyUrl(array('controller' => ($this->routeNames('controller') == 'index' ? 'index' : 'catalog-'.$this->sessionGet('catalog')), 'action' => 'search', 'type' => $item['id'], 'id' => null, 'page' => null), array(), true)); ?>"<?php echo((isset($advertsType) && $advertsType == $item['id']) ? ' class="active"' : ''); ?>>
                    <?php echo $item['name']; ?>
                </a>
            </li>
        <?php } ?>
    <?php } ?>
</ul>
<div class="tab-content uslugi">
    <div id="tab1">
        <fieldset>
            <div class="searchholder">
                <input class="searchfield" type="text" maxlength="100" placeholder="Поиск..." value="<?php echo (isset($searchText)) ? $searchText : ''; ?>" name="search_text">
                <a class="btn-search">найти</a>
                <input type="hidden" name="search-form" value="0">
                <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('controller' => 'catalog-uslugi', 'action' => 'search-validator'))); ?>">
            </div>
        </fieldset>
    </div>
    <div id="tab2"></div>
</div>