<?php if ((isset($getGallery) && is_array($getGallery))) { ?>
<div class="item-gallery">
    <div class="left-bar">
        <a class="btn-prev">previous</a>
        <div class="pager-holder">
            <ul class="pager">
                <?php foreach ($getGallery as $item) { ?>
                    <li>
                        <a><img src="<?php echo($item['slider']['small_gallery']); ?>" alt="slide"/></a>
                    </li>
                <?php } ?>

            </ul>
        </div>
        <a class="btn-next">next</a>
    </div>
    <div class="holder">
        <ul>
            <?php foreach ($getGallery as $item) { ?>
                <li>
                    <a href="<?php echo ($item['url']); ?>" data-lightbox="place-gallery">
                        <img src="<?php echo($item['slider']['medium']); ?>" alt="slide"/></a>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php } ?>