<form class="form-validator add" action="<?php echo($this->easyUrl(array('action' => 'add'))); ?>" method="post" enctype="multipart/form-data">
  <fieldset>
    <legend>Добавление поста</legend>
    <div class="control-group">        
        <label class="control-label">Заголовок</label>
        <div class="controls">
            <input class="span5" type="text" name="title" placeholder="Введите текст…" maxlength="250" value="">
        </div>
    </div>
    <div class="control-group">        
        <label class="control-label">Текст</label>
        <div class="controls">
            <textarea name="description" class="textarea-fix-size span5 tinymce" maxlength="20000" placeholder="Введите текст…" rows="10"></textarea>
        </div>
    </div>
    <label>Картинка</label>
    <input type="file" name="img" value="">
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Сохранить</button>
      <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'index'))); ?>">Отменить</a>
    </div>
  </fieldset>
  <input type="hidden" name="add-form" value="0">
  <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
</form>
