<div class="row-fluid">
    <div class="col">        
        <a class="btn btn-primary" href="<?php echo($this->easyUrl(array('action' => 'add'))); ?>">Добавить</a>
    </div>
</div> 
<br>
<?php if($blogList){ ?>
<div class="row-fluid">
    <div class="col">      
        <table class="table table-striped table-bordered">
            <thead>        
                <tr>
                    <th>Дата</th>
                    <th>Заголовок</th>
                    <th class="action-box"></th>
                </tr>
            </thead>
            <?php foreach($blogList as $item){ ?>
            <tr>
                <td><?php echo($item['date']); ?></td>
                <td><?php echo($item['title']); ?></td>
                <td class="action-box">
                   <a href="<?php echo($this->easyUrl(array('action' => 'edit', 'id' => $item['id']))) ?>" class="icon-edit" title="редактировать"></a>
                   <a href="<?php echo($this->easyUrl(array('action' => 'remove', 'id' => $item['id']))) ?>" class="icon-remove confirm-remove" title="удалить"></a>
                </td>
            </tr>
            <?php } ?> 
        </table>
        <?php echo($this->partial('admin-partials/paginator.phtml', array('paginator' => $paginator))); ?>
    </div>
</div>
<?php } ?>