<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Такси 5 Звезд'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <!-- Le styles -->
        <?php 
            $this->headLink(array(
                         'rel' => 'shortcut icon', 
                         'type' => 'image/vnd.microsoft.icon', 
                         'href' => $this->basePath() . '/img/favicon.ico'
                  ))
                  ->prependStylesheet($this->basePath() . '/css/error.css')
                  ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                  ->prependStylesheet($this->basePath() . '/css/style.css')
                  ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css'); 



            $this->headScript()
                 ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                 ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                 ->prependFile($this->basePath() . '/js/jquery.min.js'); 
            
            echo($this->headLink()."\n");
            echo($this->headScript()."\n");
        ?>
    </head>
    <body>
        <div class="container">
            <?php echo($this->content); ?>
        </div> <!-- /container -->
        <?php echo($this->inlineScript()); ?>
    </body>
</html>
