<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Error'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php 
            $this->headLink(array(
                         'rel' => 'shortcut icon', 
                         'type' => 'image/vnd.microsoft.icon', 
                         'href' => $this->basePath() . '/images/favicon.ico'
                  ))
                  ->prependStylesheet($this->basePath() . '/css/error.css')
                  ->prependStylesheet($this->basePath() . '/css/style.css'); 
            
            echo($this->headLink()."\n");
        ?>
    </head>
    <body>
        <div class="container">
            <?php echo($this->content); ?>
        </div> <!-- /container -->
        <?php echo($this->inlineScript()); ?>
    </body>
</html>
