<?php if(isset($breadcrumbs) && is_array($breadcrumbs)){ $first = true; ?>
    <?php foreach($breadcrumbs as $item) { ?>
    <?php if($first == true){ $first=false; }else{ ?> » <?php } ?>
    <a href="<?php echo($this->easyUrl(array('module' => 'application', 'controller' => (isset($controller) ? $controller : 'catalog-'.$breadcrumbs[0]['url']), 'action' => 'search', 'category' => $item['url']), array(), true)); ?>"><?php echo($item['name']); ?></a>
    <?php } ?>
<?php } ?> 