<div class="wrapper">
    <div class="wrapper-center">
        <div class="container">
            <h2 class="lk-title">Сообщения</h2>
            <?php if ($outboxList) { ?>
                <table>
                    <tr>
                        <th>Заголовок</th>
                        <th>Кому</th>
                        <th>Текст</th>
                        <th>Дата</th>
                    </tr>
                    <?php foreach ($outboxList as $item) { ?>
                        <tr>
                            <td><?php echo $item['title']; ?></td>
                            <td><?php echo $item['username']; ?></td>
                            <td><?php echo $item['text']; ?></td>
                            <td><?php echo $item['timestamp']; ?></td>
                            <td><a href="">Удалить</a></td>
                            <input class="remove-message" type="hidden" name="message_id" value="<?php echo $item['id']; ?>"/>
                        </tr>
                    <?php } ?>
                </table>
                <input type="hidden" name="delete_url" value="<?php echo $this->easyUrl(array('action' => 'delete', 'message-id' => $item['id']))?>"/>
                <input type="hidden" name="action" value="outbox"/>
            <?php } ?>
        </div>
    </div>
</div>