<div id="main" class="no-bg no-pad">
    <div class="container">
        <div class="subnav">
            <a href="<?php echo($this->easyUrl(array('action' => 'index'), array('opendialog' => $advertId ))); ?>" class="back">Вернуться</a>
            <div class="subnav-title group">
                <img src="<?php echo($this->easyUrl(array('module' => 'application', 'controller' => 'image', 'action' => 'adverts-gallery', 'id' => $images[0]['id'], 'w' => 61, 'h' => 61, 'crop' => 'y'))); ?>"/>
                <div class="description">
                    <a href="<?php echo($this->easyUrl(array('module' => 'application', 'controller' => 'adverts', 'action' => 'view', 'id' => $advertId))); ?>"><?php echo($advert['name']); ?></a>
                </div>
            </div>
            <a href="<?php echo($this->easyUrl(array('action' => 'delete', 'from-user' => $this->session('profile')->authId, 'to-user' => $user['id']))); ?>" class="delete-all">удалить все сообщения</a>
        </div>
        <section class="chat group">
            <?php if ($messagesList) { ?>
                    <?php foreach ($messagesList as $item) { ?>
                        <?php if ($item['username'] == $item['from_username']) { ?>
                            <article class="author1">
                                <div class="post-header group">
                                    <?php echo $user['name']; ?>
                                    <span class="date"><b>Дата:</b><?php echo($item['timestamp']); ?></span>
                                </div>
                                <div class="text">
                                    <?php echo $item['text']; ?>
                                </div>
                            </article>
                        <?php }else{?>
                            <article class="author2">
                                <div class="post-header group">
                                    Ваше сообщение
                                    <span class="date"><b>Дата:</b><?php echo($item['timestamp']); ?></span>
                                </div>
                                <div class="text">
                                    <?php echo $item['text']; ?>
                                </div>
                            </article>
                        <?php }?>
                    <?php } ?>
                <?php } ?>
            <article class="author2">
                <div class="post-header group">
                    <b>Написать сообщение</b>
                </div>
                <div class="text group">
                    <form id="form-talk-add" class="form-validator" action="<?php echo($this->easyUrl(array('action' => 'add'))); ?>" method="post" enctype="multipart/form-data">
                        <textarea name="text" placeholder="Введите ваше сообщение &#8230;"></textarea>
                        <a class="submit_talk">Отправить</a>
                        <input type="hidden" name="to_user_id" value="<?php echo $user['id']; ?>">
                        <input type="hidden" name="advert_id" value="<?php echo $advertId; ?>">
                        <input type="hidden" name="add-form" value="0">
                        <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
                    </form>
                </div>
            </article>
        </section>
        </div>
    </div>
</div>