<a href="<?php echo $this->easyUrl(array('action' => 'add'))?>" class="btn btn-primary">Добавить баннер</a>
<hr>
<?php if ($bannersList) { ?>
    <div class="row-fluid">
        <div class="col">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Название</th>
                    <th>URL</th>
                    <th class="action-box"></th>
                </tr>
                </thead>
                <?php foreach ($bannersList as $item) { ?>
                    <tr>
                        <td><?php echo($item['title']); ?></td>
                        <td><?php echo($item['url']); ?></td>
                        <td class="action-box">
                            <a href="<?php echo($this->easyUrl(array('action' => 'edit', 'id' => $item['id']), array(), true)) ?>" class="icon-edit" title="редактировать"></a>
                            <a href="<?php echo($this->easyUrl(array('action' => 'remove', 'id' => $item['id']), array(), true)) ?>" class="icon-remove confirm-remove" title="удалить"></a>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
    </div>
<?php } ?>