<?php if($getEdit){ ?>
    <form class="form-validator edit" action="<?php echo($this->easyUrl(array('id' => $getEdit['id']))); ?>" method="post">
        <fieldset>
            <legend><?php echo($getEdit['title']); ?></legend>
            <div class="control-group">
                <label class="control-label">Текст</label>
                <div class="controls">
                    <textarea name="content" class="textarea-fix-size span5 tinymce" maxlength="20000" placeholder="Введите текст…" rows="20"><?php echo($getEdit['content']); ?></textarea>
                </div>
            </div>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'index'))); ?>">Отменить</a>
            </div>
        </fieldset>
        <input type="hidden" name="edit-form" value="0">
        <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
    </form>
<?php }else{ ?>
    <h3>Нет данных</h3>
<?php } ?>