        <div class="footer-menu container">
            <div class="col">
                <h4>Site Name</h4>
                <ul>
                    <li><a href="<?php echo($this->easyUrl(array('module' => 'application', 'controller'=>'about-us'))); ?>">О Компании</a></li>
                    <li><a href="<?php echo($this->easyUrl(array('module' => 'application', 'controller'=>'testimonials'))); ?>">Отзывы</a></li>
                    <li><a href="<?php echo($this->easyUrl(array('module' => 'application', 'controller'=>'contact-us'))); ?>">Контакты</a></li>
                </ul>
            </div>
            <div class="col">
                <h4>Ресурсы</h4>
                <ul>
                    <li><a href="#">Добавить</a></li>
                </ul>
            </div>
            <div class="col">
                <h4>Приложения</h4>
                <ul>
                    <li class="ico ico01"><a href="<?php echo($this->basePath('/')); ?>">Для Android</a></li>
                    <li class="ico ico02"><a href="<?php echo($this->basePath('/')); ?>">Для iOS</a></li>
                </ul>
            </div>
            <div class="col">
                <h4>Социальные сети</h4>
                <ul>
                    <li class="ico ico03"><a href="http://vk.com/" target="_blank">Вконтакте</a></li>
                    <li class="ico ico08"><a href="http://www.youtube.com/" target="_blank">YouTube</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<footer class="footer">
    <div>&copy; <?php echo(date('Y')); ?> «Site Name». Все права защищены.</div>
</footer>