<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php             
            $this->headTitle($this->siteName())
                 ->setSeparator(' - ')
                 ->setAutoEscape(false);
               
            echo($this->headTitle());
        ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <!-- styles and js -->
        <?php 
           $this->headLink(array(
                       'rel' => 'shortcut icon', 
                       'type' => 'image/png', 
                       'href' => $this->basePath() . '/img/favicon.png'
                ))
                ->appendStylesheet($this->basePath() . '/css/jcf.css')
                ->appendStylesheet($this->basePath() . '/css/lightbox.css')
                ->appendStylesheet($this->basePath() . '/fonts/stylesheet.css');

            $this->headScript()
                 ->appendFile($this->basePath() . '/js/libs/jquery-1.10.2.min.js')
                 ->appendFile($this->basePath() . '/js/libs/modernizr-2.6.2.min.js') 
                 ->appendFile($this->basePath() . '/js/libs/lightbox-2.6.min.js')
                 ->appendFile($this->basePath() . '/js/libs/jcf.js')
                 ->appendFile($this->basePath() . '/js/jquery.main.js') 
                 ->appendFile($this->basePath() . '/js/jquery.carousel.js')
                 ->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                 ->appendFile($this->basePath() . '/js/default.js');

            $this->mediaLoader();
            
            echo($this->headLink()."\n");
            echo($this->headScript()."\n");
        ?>
    </head>
    <body>
        <div class="wrapper">
            <div class="wrapper-center">
                <?php echo($this->partial('application/layout/header')); ?>
                <div class="container">
                    <?php echo($this->content); ?>
                </div>
        <!-- /container -->
        <?php echo($this->partial('application/layout/footer')); ?>
        <?php echo($this->inlineScript()); ?>
    </body>
</html>