<footer class="footer">
    <div>
        <ul class="sub-nav">
            <li><a href="#" class="logo3-holder"><div class="logo3">&copy; Uslugi.kz</div></a></li>
        </ul>
        <ul class="sub-nav">
            <li><a href="<?php echo($this->easyUrl(array('module' => 'application', 'controller' => 'about-us'))); ?>">О нас</a></li>
            <li><a href="<?php echo($this->easyUrl(array('module' => 'application', 'controller' => 'contact-us'))); ?>">Обратная связь</a></li>
            <li><a href="<?php echo($this->easyUrl(array('module' => 'profile', 'controller' => ($this->session('profile')->authId !== null ? 'index' : 'guest'), 'action' => 'add'))); ?>">Добавить обьявление</a></li>
        </ul>
        <ul class="socials">
            <li><a href="http://vk.com/" class="vk" target="_blank">vk</a></li>
            <li><a href="http://chisw.us/" class="chi" target="_blank">chi</a></li>
        </ul>
    </div>
</footer>