<div class="row-fluid">
    <div class="col span5">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Тип сообщения</th>
                <th>Тема</th>
                <th class="action-box"></th>
            </tr>
            </thead>
            <?php foreach($notificationsList as $item){ ?>
                <tr>
                    <td><?php echo $item['url']; ?></td>
                    <td><?php echo $item['title']; ?></td>
                    <td class="action-box">
                        <a href="<?php echo($this->easyUrl(array('action' => 'edit', 'id' => $item['id']))); ?>" class="icon-edit" title="редактировать"></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>