<?php if($getEdit){ ?>
<form class="edit-form" action="<?php echo($this->easyUrl(array('id' => $getEdit['id']))); ?>" method="post">
  <fieldset>
    <legend>Редактирование пользователя</legend>
    <div class="control-group">        
        <label class="control-label">Имя</label>
        <div class="controls">
            <input class="span3" type="text" name="name" placeholder="Введите текст…" maxlength="100" value="<?php echo($getEdit['name']); ?>">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Эл. почта</label>
        <div class="controls">            
            <input class="span3" type="email" name="username" placeholder="Введите текст…" maxlength="100" value="<?php echo($getEdit['username']); ?>" autocomplete="off">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Новый пароль</label>
        <div class="controls">            
            <input class="span3" type="password" name="password" placeholder="Введите текст…" maxlength="100" value="" autocomplete="off">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Повторите пароль</label>
        <div class="controls">            
            <input class="span3" type="password" name="retry_password" placeholder="Введите текст…" maxlength="100" value="" autocomplete="off">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Счет</label>
        <div class="controls">            
            <input class="span1 num-only" type="text" name="balance" placeholder="Цифра…" maxlength="20" value="<?php echo((int)$getEdit['balance']); ?>">
            <p><small>Максимальная длина 9 символов</small></p>
        </div>
    </div>
    <?php echo($this->partial('admin-partials/user-phone-box.phtml')); ?>
    <div class="control-group">  
        <hr>
        <label class="checkbox">
            <input type="checkbox" name="status" value="y"<?php echo(($getEdit['status'] == 'y') ? ' checked="checked"' : ''); ?>> Статус "Активный"
        </label>
        <hr>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Сохранить</button>
      <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'index'))); ?>">Отменить</a>
    </div>
  </fieldset>
  <input type="hidden" name="edit-form" value="0">
  <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator', 'user' => $getEdit['id']))); ?>">
</form>
<?php }else{ ?>
<h3>Нет данных</h3>
<?php } ?>
