<?php if($getEdit){ ?>
<form class="edit-form" action="<?php echo($this->easyUrl(array('id' => $getEdit['id']))); ?>" method="post">
  <fieldset>
    <legend>Редактирование пользователя</legend>
    <div class="control-group">        
        <label class="control-label">Имя</label>
        <div class="controls">
            <input class="span3" type="text" name="name" placeholder="Введите текст…" maxlength="100" value="<?php echo($getEdit['name']); ?>">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Эл. почта</label>
        <div class="controls">            
            <input class="span3" type="email" name="username" placeholder="Введите текст…" maxlength="100" value="<?php echo($getEdit['username']); ?>" autocomplete="off">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Новый пароль</label>
        <div class="controls">            
            <input class="span3" type="password" name="password" placeholder="Введите текст…" maxlength="100" value="" autocomplete="off">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Повторите пароль</label>
        <div class="controls">            
            <input class="span3" type="password" name="retry_password" placeholder="Введите текст…" maxlength="100" value="" autocomplete="off">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Звезд</label>
        <div class="controls">            
            <input class="span1" type="text" name="star" placeholder="Цифра…" maxlength="4" value="<?php echo((int)$getEdit['star']); ?>">
        </div>
    </div>
    <?php echo($this->partial('admin-partials/user-phone-box.phtml')); ?>
    <div class="control-group">
        <label class="control-label">Объявления в разделах</label>
        <div class="row-fluid">            
            <div class="col span3">            
            <?php if(isset($carsCount) && is_array($carsCount)){ ?>
                <?php if(count($carsCount) > 0){ ?>
                <ul class="nav nav-pills nav-stacked">
                    <?php foreach($carsCount as $item){ ?>
                    <li><a href="<?php echo($this->easyUrl(array('controller' => $item['url'], 'action' => 'index', 'user' => $getEdit['id']))); ?>"><?php echo($item['name'].' ('.$item['count'].')'); ?></a></li>
                    <?php } ?>
                </ul>
                <?php }else{ ?>
                <h5>нет объявлений</h5>
                <?php } ?>
            <?php } ?>
            </div>
        </div>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Сохранить</button>
      <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'index'))); ?>">Отменить</a>
    </div>
  </fieldset>
  <input type="hidden" name="edit-form" value="0">
  <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator', 'user' => $getEdit['id']))); ?>">
</form>
<?php }else{ ?>
<h3>Нет данных</h3>
<?php } ?>
