<form class="category-form-validator add" action="<?php echo($this->easyUrl(array('action' => 'category-add'))); ?>" method="post">
  <fieldset>
    <legend>Добавление категории</legend>
    <div class="control-group">
        <label class="control-label">Родительская категория</label>
        <div class="controls">
            <select class="selectpicker span3" name="category_id">
              <option value="1">-- Главная --</option>
              <?php echo($this->partial('admin/catalog/category/add-category-select.phtml', array('categoryList' => $categoryList, 'tab' => ''))); ?>
            </select>
        </div>
    </div>
    <div class="control-group">        
        <label class="control-label">Название</label>
        <div class="controls">
            <input type="text" name="name" class="span3" placeholder="Введите текст…" maxlength="50" value="">
        </div>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Сохранить</button>
      <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'category'))); ?>">Отменить</a>
    </div>
  </fieldset>
  <input type="hidden" name="add-form" value="0">
  <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'category-validator'))); ?>">
</form>
