<?php if($getEdit){ ?>
<form class="category-form-validator edit" action="<?php echo($this->easyUrl(array('id' => $getEdit['id']))); ?>" method="post">
  <fieldset>
    <legend>Редактирование категории</legend>
    <div class="control-group">
        <label class="control-label">Родительская категория</label>
        <div class="controls">
            <select class="selectpicker span3" name="category_id">
              <option value="1">-- Главная --</option>
              <?php echo($this->partial('admin/catalog/category/edit-category-select.phtml', array('categoryList' => $categoryList, 'parent_id' => $getEdit['parent_id'], 'tab' => ''))); ?>
            </select>
        </div>
    </div>
    <div class="control-group">        
        <label class="control-label">Название</label>
        <div class="controls">
            <input type="text" name="name" class="span3" placeholder="Введите текст…" maxlength="50" value="<?php echo($getEdit['name']); ?>">
        </div>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Сохранить</button>
      <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'category'))); ?>">Отменить</a>
    </div>
  </fieldset>
  <input type="hidden" name="edit-form" value="0">
  <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'category-validator'))); ?>">
</form>
<?php }else{ ?>
<h3>Нет данных</h3>
<?php } ?>
