<div class="wrapper">
    <div class="wrapper-center">
        <div class="container">
            <div class="lk">
            <?php echo($this->partial('profile-partials/tabs-menu.phtml')); ?>
            <div class="tab-content">
                <section class="tab-item">
                    <div class="section-content">
                        <h6 class="centered">Вы успешно пополнили счет.</h6>
                    </div>
                </section>
            </div>
        </div>
        </div>
    </div>
</div>