
<div class="row-fluid">
    <div class="col">      
        <table class="table table-striped table-bordered">
            <thead>        
                <tr>
                    <th colspan="2">Количество элементов в кэше:</th>
                </tr>
            </thead>
                <tr>
                    <td>Папок</td>
                    <td><?php echo($dir_count); ?></td>
                </tr>
                <tr>
                    <td>Файлов</td>
                    <td><?php echo($file_count); ?></td>
                </tr>
        </table>
        <a class="btn btn-primary" href="<?php echo($this->easyUrl(array('action' => 'remove'))); ?>">Очистить</a>
    </div>
</div>