<div class="wrapper">
    <div class="wrapper-center">
        <div class="container">
            <h2 class="lk-title">Ошибка</h2>

            <div class="lk">
                <div class="tab-content uslugi kab">
                    <div class="error-text" id="tab3">
                        При добавлении произошла ошибка!
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>