<div class="wrapper">
    <div class="wrapper-center">
        <div class="container">
            <h2 class="lk-title">Добавление объявления</h2>

            <div class="lk">
                <div class="tab-content uslugi kab guest">
                    <div id="tab3">
                        Объяление успешно добавлено, вам на почту было отправлено письмо c ссылкой для поддтверждения.<br>
                        Для активации объявления пройдите по ссылке для подтверждения.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>