<div id="main">
<div class="container top-container group">
   <?php echo($this->partial('/partials/main-holder.phtml')); ?>
    <div class="content">
        <section class="name">
            <h1>Uslugi.kz — решения
                <span>на все случаи жизни!</span>
            </h1>
        </section>

    </div>
</div>
<section class="opportunities">
    <div class="opp-container">
        <ul>
            <li><a href="#">
                    <div class="img-holder">
                        <span class="propose"></span>
                    </div>
                    <p>Просмотр предложений без регистрации </p>
                </a></li><li class="active">
                <a href="#">
                    <div class="img-holder">
                        <span class="amount"></span>
                    </div>
                    <p>Неограниченное количество объявлений</p>
                </a></li><li>
                <a href="#">
                    <div class="img-holder">
                        <span class="safety"></span>
                    </div>
                    <p>Высокая надежность каждой сделки</p>
                </a></li><li>
                <a href="#">
                    <div class="img-holder">
                        <span class="administration"></span>
                    </div>
                    <p>Удобное управление обьявлениями</p>
                </a></li>
        </ul>
    </div>
</section>
<section class="last-added">
    <div class="container">
        <h1>Последние добавленные</h1>
        <ul class="group">
            <li>
                <article class="post group clickable">
                    <div class="image_holder">
                        <img src="images/temp/image.jpg" alt="img">
                    </div>
                    <div class="text_info">
                        <div class="article_title group">
                            <span class="price">Цена от: </span>
                            <span class="sum"> 9000 <span class="colored">тг.</span></span>

                        </div>
                        <span class="date">3.27.2014</span>
                        <p class="main-info">
                            Hummer H2
                        </p>
                        <div class="details">
                            <p><span>цвет авто: </span>черный</p>
                            <p><span>год авто: </span>2003</p>
                        </div>
                    </div>
                </article>
            </li>
            <li>
                <article class="post group clickable">
                    <div class="image_holder">
                        <img src="images/temp/image.jpg" alt="img">
                    </div>

                    <div class="text_info">
                        <div class="article_title group">
                            <span class="price">Цена:</span>
                            <span class="sum">договорная</span>
                        </div>
                        <span class="date">3.27.2014</span>
                        <p class="main-info">
                            Ремонт техники
                        </p>
                        <address>Все регионы</address>
                    </div>
                </article>
            </li>
            <li>
                <article class="post group clickable">
                    <div class="image_holder">
                        <img src="images/temp/image.jpg" alt="img">
                    </div>
                    <div class="text_info">
                        <div class="article_title group">
                            <span class="price">Цена:</span>
                            <span class="sum">150 <span class="colored">$</span></span>

                        </div>
                        <span class="date">3.27.2014</span>
                        <p class="main-info">
                            Квартира студия, 1комната
                        </p>
                        <address>Астана, ул. Чингиза Айтматова 20</address>
                    </div>
                </article>
            </li>
            <li>
                <article class="post group clickable">
                    <div class="image_holder">
                        <img src="images/temp/image.jpg" alt="img">
                    </div>
                    <div class="text_info">
                        <div class="article_title group">
                            <span class="price">Цена:</span>
                            <span class="sum">150 $</span>

                        </div>
                        <address>Астана, ул. Чингиза Айтматова 20</address>
                    </div>
                </article>
            </li>
            <li>
                <article class="post group clickable">
                    <div class="image_holder">
                        <img src="images/temp/image.jpg" alt="img">
                    </div>
                    <div class="text_info">
                        <div class="article_title group">
                            <span class="price">Цена:</span>
                            <span class="sum">150 $</span>

                        </div>
                        <address>Астана, ул. Чингиза Айтматова 20</address>
                    </div>
                </article>
            </li>
            <li>
                <article class="post group clickable">
                    <div class="image_holder">
                        <img src="images/temp/image.jpg" alt="img">
                    </div>
                    <div class="text_info">
                        <div class="article_title group">
                            <span class="price">Цена:</span>
                            <span class="sum">150 $</span>

                        </div>
                        <address>Астана, ул. Чингиза Айтматова 20</address>
                    </div>
                </article>
            </li>
        </ul>
    </div>
</section>
<section class="main-content">
    <div class="main-content-holder group">
        <h1>
            <span>наши рубрики</span>
        </h1>
        <h3>Мы предлагаем новый сервис бесплатных обьявлений.
            <span>У нас вы найдете:</span>
        </h3>

        <article class="rubric services">
            <div class="visual fl-left">
                <img src="images/img-rubr3.png" alt="#"/>
                <span>Услуги</span>
            </div>
            <div class="text">
                <h4><a href="#">Услуги</a></h4>
                <p>
                    Услуги могут быть: частные или коммерческие, добровольные или вынужденные, платные или бесплатные, мгновенные или длительные, взаимные и анонимные, государственные и т. д.
                    Обобщающей категорией, которая включает в себя все виды коммерческих и некоммерческих услуг и составляет часть экономики, является сфера услуг.
                </p>
            </div>
        </article>
        <article class="rubric estate">
            <div class="visual fl-right">
                <img src="images/img-rubr5.png" alt="#"/>
                <span>Недвижимость</span>
            </div>
            <div class="text">
                <h4><a href="#">Недвижимость</a></h4>
                <p>
                    Аренда (лат. arrendare — отдавать в наём) — форма имущественного договора, при которой собственность передаётся во временное владение и пользование (или только во временное пользование) арендатору за арендную плату. Например, в сельском хозяйстве и добывающих отраслях оплачивается временное пользование землёй или недрами. Включает земельную ренту, амортизацию процента за пользование материальными активами. Плоды, продукция и доходы, полученные арендатором в результате использования арендованного имущества в соответствии с договором, являются его собственностью.
                </p>
            </div>
        </article>
        <article class="rubric rent group">
            <div class="visual fl-left">
                <img src="images/img-rubr2.png" alt="#"/>
                <span>Аренда</span> <span>авто</span>
            </div>
            <div class="text">
                <h4><a href="#">Аренда авто</a></h4>
                <p>
                    Аренда транспортных средств — один из видов арендных отношений, основывающийся на
                    договоре аренды транспортных средств, который подразделяется на:</p>

                <p>- договор аренды транспортного средства (фрахтования на время) с экипажем, по которому
                    арендодатель предоставляет его арендатору во временное владение и пользование за плату и при
                    этом оказывает своими силами услуги по управлению им и технической эксплуатации;</p>

                <p>- аналогичный договор, но без экипажа и предоставления дополнительных услуг</p>
            </div>
        </article>

        <article class="rubric  group">


        </article>

        <article class="rubric job group">
            <div class="visual fl-right">
                <img src="images/img-rubr4.png" alt="#"/>
                <span>Работа</span>
            </div>
            <div class="text">
                <h4><a href="#">Работа</a></h4>
                <p>Работа - это процесс, требующий приложения умственных или физических усилий, который целью своей ставит получение определенного результата. Именно работа, как правило, определяет социальный статус человека. И является, по сути, главным двигателем прогресса в обществе. Работа, как явление, присуще только живым организмам и прежде всего человеку.
                </p>
            </div>
        </article>

    </div>
</section>
<div class="mailing">
    <div class="container">
        <h2>Рассылка новостей и новых услуг</h2>
        <div class="mailling-holder">
            <form method="post" action="<?php echo $this->easyUrl(array('action' => 'add-subscribe'))?>" class="srch">
                <fieldset>
                    <div class="searchholder">
                        <input class="searchfield" type="text" name="subscribe_email" value="" placeholder="Введите свою эл. почту" maxlength="100">
                        <input type="hidden" name="subscribe-form" value="0">
                        <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
                        <a class="btn-search">подписаться</a>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>

</div>
<section class="testimonial">
    <div class="container">
        <h1>
            <span>отзывы</span>
        </h1>
        <h3>Мы стремимся к повышению уровня сервиса.
            <span>Поэтому нам важно Ваше мнение.</span>
        </h3>
        <div class="testimonial-post t-dotted">
            <img src="images/temp/avka1.png" alt="#"/>
            <div class="text">
                <span class="name">Ирина</span>
                <span class="time">25 июня 2013, 01:21</span>
                <p>Текст-«рыба» (также текст-заполнитель или текст-манекен) — на жаргоне дизайнеров текст, вставляемый в макет и не несущий смысловой нагрузки. Обладает некоторыми свойствами осмысленного текста, но является случайно сгенерированным, либо взятым из открытых источников (не путать с плагиатом). Некоторые тексты вошли в историю, например, отрывок из текста Lorem ipsum, написанный Цицероном на латинском языке в 45 году до н. э.</p>
            </div>
        </div>
        <div class="testimonial-post t-dotted">
            <img src="images/temp/avka2.png" alt="#"/>
            <div class="text">
                <span class="name">Алекс</span>
                <span class="time">24 июня 2013, 01:21</span>
                <p>	Текст-«рыба» (также текст-заполнитель или текст-манекен) — на жаргоне дизайнеров текст, вставляемый в макет и не несущий смысловой нагрузки. Обладает некоторыми свойствами осмысленного текста, но является случайно сгенерированным, либо взятым из открытых источников (не путать с плагиатом).</p>
            </div>
        </div>
        <div class="testimonial-post">
            <img src="images/temp/avka1.png" alt="#"/>
            <div class="text">
                <span class="name">Лира Корн</span>
                <span class="time">25 июня 2013, 01:21</span>
                <p>А знаете, что я вам скажу? ;-) Съешь ещё этих мягких французских булок, да выпей же чаю))).</p>
            </div>
        </div>
    </div>
</section>
</div>