<div class="wrapper start-page">
    <div class="wrapper-center">
    <section class="name">
        <h1>Uslugi.kz — решения
            <span>на все случаи жизни!</span>
        </h1>
    </section>
        <div class="container">
            <form class="srch" type="text" maxlength="100" action="<?php echo($this->easyUrl(array('controller' => 'catalog-uslugi', 'action' => 'search', 'type' => ($advertsType > 0 ? $advertsType : null)))); ?>" method="post">
            <?php echo($this->partial('/partials/main-holder.phtml')); ?>
            </form>
        </div>
        <section class="opportunities">
                <div class="opp-container">
                    <ul>
                        <li><a href="#">
                                <div class="img-holder">
                                    <img src="/images/img-opp1.png" alt="#"/>
                                </div>
                                <p>Просмотр предложений без регистрации </p>
                            </a></li>
                        <li>
                            <a href="#">
                                <div class="img-holder">
                                    <img src="/images/img-opp2.png" alt="#"/>
                                </div>
                                <p>Неограниченное количество объявлений</p>
                            </a></li>
                        <li>
                            <a href="#">
                                <div class="img-holder">
                                    <img src="/images/img-opp3.png" alt="#"/>
                                </div>
                                <p>Высокая надежность каждой сделки</p>
                            </a></li>
                        <li>
                            <a href="#">
                                <div class="img-holder">
                                    <img src="/images/img-opp4.png" alt="#"/>
                                </div>
                                <p>Удобное управление обьявлениями</p>
                            </a></li>
                    </ul>
                </div>
            </section>

        
            <a name="services"></a> 
            <section class="main-content">
                <div class="main-content-holder">
                    <h1>
                        <span>наши рубрики</span>
                    </h1>

                    <h3>Мы предлагаем новый сервис бесплатных обьявлений.
                        <span>У нас вы найдете:</span>
                    </h3>
                    <article class="rubric rent">
                        <div class="visual fl-right">
                            <img src="/images/img-rubr2.png" alt="#"/>
                            <span>Аренда</span> <span>авто</span>
                        </div>
                        <div class="text">
                            <h4><a href="#">Аренда авто</a></h4>

                            <p>
                                Аренда транспортных средств — один из видов арендных отношений, основывающийся на
                                договоре аренды транспортных средств, который подразделяется на:

                                - договор аренды транспортного средства (фрахтования на время) с экипажем, по которому
                                арендодатель предоставляет его арендатору во временное владение и пользование за плату и
                                при
                                этом оказывает своими силами услуги по управлению им и технической эксплуатации;

                                - аналогичный договор, но без экипажа и предоставления дополнительных услуг</p>
                        </div>
                    </article>
                    <article class="rubric services">
                        <div class="visual fl-left">
                            <img src="/images/img-rubr3.png" alt="#"/>
                            <span>Услуги</span>
                        </div>
                        <div class="text">
                            <h4><a href="#">Услуги</a></h4>

                            <p>
                                Услуги могут быть: частные или коммерческие, добровольные или вынужденные, платные или
                                бесплатные, мгновенные или длительные, взаимные и анонимные, государственные и т. д.
                                Обобщающей категорией, которая включает в себя все виды коммерческих и некоммерческих
                                услуг и составляет часть экономики, является сфера услуг.
                            </p>
                        </div>
                    </article>
                    <article class="rubric job">
                        <div class="visual fl-right">
                            <img src="/images/img-rubr4.png" alt="#"/>
                            <span>Работа</span>
                        </div>
                        <div class="text">
                            <h4><a href="#">Работа</a></h4>

                            <p>
                                Работа - это процесс, требующий приложения умственных или физических усилий, который
                                целью своей ставит получение определенного результата. Именно работа, как правило,
                                определяет социальный статус человека. И является, по сути, главным двигателем прогресса
                                в обществе. Работа, как явление, присуще только живым организмам и прежде всего
                                человеку.</p>
                        </div>
                    </article>
                    <article class="rubric estate">
                        <div class="visual fl-left">
                            <img src="/images/img-rubr5.png" alt="#"/>
                            <span>Услуги</span>
                        </div>
                        <div class="text">
                            <h4><a href="#">Недвижимость</a></h4>

                            <p>
                                Аренда (лат. arrendare — отдавать в наём) — форма имущественного договора, при которой
                                собственность передаётся во временное владение и пользование (или только во временное
                                пользование) арендатору за арендную плату. Например, в сельском хозяйстве и добывающих
                                отраслях оплачивается временное пользование землёй или недрами. Включает земельную
                                ренту, амортизацию процента за пользование материальными активами. Плоды, продукция и
                                доходы, полученные арендатором в результате использования арендованного имущества в
                                соответствии с договором, являются его собственностью.
                            </p>
                        </div>
                    </article>
                </div>
            </section>
            <div class="mailing">
                <h2>Рассылка новостей и новых услуг</h2>

                <div class="mailling-holder">
                    <form class="subscribe srch" method="post" action="<?php echo $this->easyUrl(array('action' => 'add-subscribe'))?>">
                        <fieldset>
                            <div class="searchholder">
                                <input class="searchfield" type="text" name="subscribe_email" value="" placeholder="Введите свою эл. почту" maxlength="100">
                                <input type="hidden" name="subscribe-form" value="0">
                                <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
                                <a class="btn-search">подписаться</a>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
            <section class="testimonial">
                <div class="testimonial-holder">
                    <h1>
                        <span>отзывы</span>
                    </h1>

                    <h3>Мы стремимся к повышению уровня сервиса.
                        <span>Поэтому нам важно Ваше мнение.</span>
                    </h3>

                    <div class="testimonial-post t-dotted">
                        <img src="/images/tmp/avka1.png" alt="#"/>

                        <div class="text">
                            <span class="name">Ирина</span>
                            <span class="time">25 июня 2013, 01:21</span>

                            <p>Текст-«рыба» (также текст-заполнитель или текст-манекен) — на жаргоне дизайнеров текст,
                                вставляемый в макет и не несущий смысловой нагрузки. Обладает некоторыми свойствами
                                осмысленного текста, но является случайно сгенерированным, либо взятым из открытых
                                источников (не путать с плагиатом). Некоторые тексты вошли в историю, например, отрывок
                                из текста Lorem ipsum, написанный Цицероном на латинском языке в 45 году до н. э.</p>
                        </div>
                    </div>
                    <div class="testimonial-post t-dotted">
                        <img src="/images/tmp/avka2.png" alt="#"/>

                        <div class="text">
                            <span class="name">Алекс</span>
                            <span class="time">24 июня 2013, 01:21</span>

                            <p> Текст-«рыба» (также текст-заполнитель или текст-манекен) — на жаргоне дизайнеров текст,
                                вставляемый в макет и не несущий смысловой нагрузки. Обладает некоторыми свойствами
                                осмысленного текста, но является случайно сгенерированным, либо взятым из открытых
                                источников (не путать с плагиатом).</p>
                        </div>
                    </div>
                    <div class="testimonial-post">
                        <img src="/images/tmp/avka1.png" alt="#"/>

                        <div class="text">
                            <span class="name">Лира Корн</span>
                            <span class="time">25 июня 2013, 01:21</span>

                            <p>А знаете, что я вам скажу? ;-) Съешь ещё этих мягких французских булок, да выпей же
                                чаю))).</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- /container -->
            <div class="popup-holder">
                <div id="popup1">
                    <section class="popup-opinion">
                        <h1>Обратная связь</h1>

                        <form>
                            <div class="col">
                                <div class="row">
                                    <label for="name1">Представьтесь</label>
                                    <input id="name1" type="text" placeholder="Имя и фамилия"/>
                                </div>
                                <div class="row">
                                    <label for="mail">Эл.почта</label>
                                    <input id="mail" type="text" placeholder="Введите эл. почту"/>
                                </div>
                                <div class="row">
                                    <label for="tel">Номер телефона</label>
                                    <input id="tel" type="text" placeholder="Введите номер телефона"/>
                                </div>
                            </div>
                            <div class="col">
                                <label for="comment">Сообщение</label>
                                <textarea name="comment" id="comment" cols="30" rows="10"
                                          placeholder="Ваш комментарий"></textarea>
                            </div>
                            <button class="sbmt-gr" value="подобрать" type="submit">отправить</button>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>




